### ISSUE TITLE
Run sorter issue

### ISSUE THREAD

**Issue by LuRodForster** [catalystneuro/feldman-lab-to-nwb#20]
Hi, 
I'm getting an error when I run the sorter cell. I've tried with both Ironclust and Kilosort2. Ironclust gives me an error of an undefined function 'pdist' and Kilosort also gives me a undefined function error  'butter'. I've checked and both are part of different Matlab toolbox:  Statistics Toolbox and Signal Processing Toolbox. I have both toolboxes installed and when I run Kilosort on Matlab it works perfectly. I'm not sure what is going on. 
Thanks for the help!

![image(1)](https://user-images.githubusercontent.com/89806364/131392464-e5acc3ea-84f1-4b1f-ba91-d96bfab611bd.png)
![image](https://user-images.githubusercontent.com/89806364/131392467-17183981-b793-4934-8972-801aa6653ffc.png)

**Comment by CodyCBakerPhD** [comment]
Attn @alejoe91

**Comment by alejoe91** [comment]
Hi @LuRodForster 

I apologize for my late reply!

The problem could be that the wrong version of matlab is run when it's launched from the terminal. 

The way spikeinterface handles MATLAB sorters, is to create a `.bat` file (for linux it's a `.sh` file) that is run "externally" (the bat file should be called `run_ironclust.bat` in the `output_folder`). In this file, MATLAB is called from the command line. 

As a first check, can you launch MATLAB normally (from the icon) and from the command line (with the `matlab` command from a cmd prompt) and check that the 2 versions are the same and that the Statistics Toolbox and Signal Processing Toolbox is installed in both? I suspect that a different matlab version is launched when running it from the terminal.

Let me know if that's the case! Then we can easily find a solution.

Cheers (and sorry again for my late reply!)

Alessio

**Comment by LuRodForster** [comment]
Hi Alessio, Thanks for the suggestion! It was definitely the Matlab version. 

Lucia

**Comment by alejoe91** [comment]
Hi Lucia! Great to hear :) so that fixed it for you and it's running as expected?
In that case I'd close the issue!

**Comment by LuRodForster** [comment]
Yes it runs fine now! You can close it 
Thanks
