### ISSUE TITLE
Convert_nwb_to_spike_mat error

### ISSUE THREAD

**Issue by LuRodForster** [catalystneuro/feldman-lab-to-nwb#21]
Hi,

I'm getting this error when I run convert_nwb_to_spikes_mat:
Error: Index (272) out of range (0-271). 
It only happens if the nwb file was made with kilosort3. I never get this error when I convert the nwb to mat if the it was made with ironclust.

Thanks for the help!

![image](https://user-images.githubusercontent.com/89806364/135356446-e74b7840-425a-45a2-97e6-690cac609b3a.png)

**Comment by CodyCBakerPhD** [comment]
@LuRodForster Cany you send me the NWBFile you made via kilosort? I've seen this type of error before but thought I had debugged it; of course, it's possible different sorters have different indexing conventions... I'll have to think of a way around that, because the channel indexing there is actually pretty important to a number of data extractions

**Comment by LuRodForster** [comment]
Hi Cody,

I'm going to send it to you by email because I can't upload it here.
Also I just realized that if I pick kilosort2.5 as the sorter if gives a different error:
![image](https://user-images.githubusercontent.com/89806364/135679076-f85ce1b8-ed30-4645-a68c-988373f3ee85.png)


I'll send you both the kilosort3 and kilosort2_5 nwb files.

Also when I make the nwb files after doing the manual sorting with phy2 and the automatic curation part of the pipeline. I get these warnings:

![image](https://user-images.githubusercontent.com/89806364/135679248-0a652e3a-4393-4903-b284-95337de252b7.png)

**Comment by CodyCBakerPhD** [comment]
@LuRodForster Thanks for sharing those files, it definitely made this a lot easier.

After digging into this, I was able to determine the source of both issues and put up PR #22 to try to fix them. The fix produces the files I emailed you, _but_ you should still make sure it works to your satisfaction by checking out that specific branch and trying to run the code again.

You can do this by navigating inside the git cloned repository and running

```
git fetch
git checkout to_spikes_fix
```

and as long as you originally installed in dev mode (`pip install -e ...`), this should now call the hopefully fixed version of the function.
